- hosts: vcs
  #remote_user: root

  tasks:

   - name: watermark png file copy
     copy:
        src: "{{ asset_root }}/vcs_conf/watermark.png"
        dest: /home/vcs/REC/
        owner: vcs
        group: vcs
