- hosts: vcs
  remote_user: root
  tasks:
#    - copy:
#        src: /root/lter_vcs_gimhae/rpm/ntp/
#        dest: /root/rpm/ntp/
    
#    - name: find rpm files and register the result
#      find:
#        paths: /root/rpm/ntp/
#        patterns: "*.rpm"
#      register: rpm_files

#    - set_fact:
#        rpm_lists: "{{ rpm_files.files | map(attribute='path') | list }}"
    
#    - name: install rpm files
#      yum:
#        name: "{{ rpm_lists }}"
#        state: present

#    - name: Stop ntp
#      systemd:
#        state: stopped
#        enabled: yes
#        name: chrony

#    - name: Add manual ntp server1
#      lineinfile:
#        path: /etc/chrony.conf
#        state: present
#        insertafter: 'server 3.centos.pool.ntp.org iburst'
#        line: "server {{ ntp_ip1 }}"

#    - name: Add manual ntp server2
#      lineinfile:
#        path: /etc/ntp.conf
#        state: present
#        insertafter: 'server 3.centos.pool.ntp.org iburst'
 #       line: "server {{ ntp_ip2 }}"

#    - name: Sync time initially with ntp_ip1
#      shell: |
#        chronydate {{ ntp_ip1 }}
#        hwclock --systohc
#      args:
#        warn: false

#    - name: Remove the default DNS server (centos)
##      lineinfile:
#        path: /etc/ntp.conf
#        state: absent
#        regexp: 'centos.pool.ntp.org iburst'

#    - name: Remove the default DNS server (rhel)
##      lineinfile:
#        path: /etc/ntp.conf
#        state: absent
#        regexp: 'rhel.pool.ntp.org iburst'

#    - name: start ntp server
#      systemd:
#        state: started
#        enabled: yes
#        name: chronyd

    - name: set timezone to Asia/Seoul
      timezone:
        name: Asia/Seoul

